algoritmo "Calculadora de impostos sobre mercadoria internacional"

var
   valor, valor2: real
inicio
      Escreval("Seja bem-vindo ao calculador de impostos sobre mercadoria internacional")
      Escreval("Digite o valor da compra em dólar ")
      Leia(valor)
      valor2 <- valor*92/100
      Escreval("O valor tributado a ser pago da compra equivale a:", valor2)
      Escreval("Totalizando um valor total de: ", valor + valor2:5:2)
fimalgoritmo
