algoritmo "contador 1 até 10 com repita"

var
   inicial, final, contador: inteiro
inicio
      Escreval("Digite o número inicial")
      Leia(inicial)
      Escreval("Digite o número final")
      Leia(final)
      contador <- inicial
      Repita
            Escreval("O contador atual é: ", contador)
            contador <- contador + 1
      Ate (contador > final)
                     

fimalgoritmo
